# Define your admin routes here
app_albums_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\AlbumController
    name_prefix: app.

app_events_api:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\EventController
    name_prefix: app.
